import { v } from "convex/values";
import { mutation, action } from "./_generated/server";
import { api } from "./_generated/api";

// 1. Mutation to create the request in DB
export const submitExchangeRequest = mutation({
  args: {
    customerName: v.string(),
    phone: v.string(),
    brand: v.string(),
    model: v.string(),
    year: v.number(),
    kilometers: v.number(),
    images: v.array(v.string()), // Simulated Cloudinary URLs
  },
  handler: async (ctx, args) => {
    // Check if customer exists or create them
    const existingCustomer = await ctx.db
      .query("customers")
      .withIndex("phone", (q) => q.eq("phone", args.phone))
      .first();

    let customerId = existingCustomer?._id;
    if (!customerId) {
      customerId = await ctx.db.insert("customers", {
        name: args.customerName,
        phone: args.phone,
        createdAt: Date.now(),
      });
    }

    // Insert exchange request
    const exchangeId = await ctx.db.insert("exchangeRequests", {
      customerId,
      customerName: args.customerName,
      phone: args.phone,
      brand: args.brand,
      model: args.model,
      year: args.year,
      kilometers: args.kilometers,
      status: "pending",
      images: args.images,
      createdAt: Date.now(),
    });

    return exchangeId;
  },
});

// 2. Mock Action for the Python FastAPI ML Prediction
export const evaluateExchangeML = action({
  args: {
    exchangeId: v.id("exchangeRequests"),
    brand: v.string(),
    year: v.number(),
    kilometers: v.number(),
  },
  handler: async (ctx, args) => {
    // In a real production app, this is where we would use ctx.runAction with fetch()
    // to call the Python FastAPI CatBoost/Vision model.
    // e.g., const res = await fetch("https://ml-api.example.com/predict", { ... })
    
    // For now, we simulate an intelligent estimation based on parameters:
    const baseValue = 1000000;
    const ageDepreciation = (new Date().getFullYear() - args.year) * 0.1 * baseValue; // 10% per year
    const kmDepreciation = (args.kilometers / 10000) * 0.05 * baseValue; // 5% per 10k km
    
    let estimatedValue = baseValue - ageDepreciation - kmDepreciation;
    
    // Add a randomized "Condition Score" generated by our "Vision Transformer"
    const conditionScore = Math.floor(Math.random() * (95 - 65 + 1)) + 65; // Score 65 - 95
    estimatedValue = estimatedValue * (conditionScore / 100);
    
    estimatedValue = Math.max(50000, Math.round(estimatedValue)); // Floor at 50k

    // Update the DB with the results via an internal mutation
    await ctx.runMutation(api.exchange.updateExchangeEvaluation, {
      exchangeId: args.exchangeId,
      estimatedValue,
      conditionScore,
    });

    return { estimatedValue, conditionScore };
  },
});

export const updateExchangeEvaluation = mutation({
  args: {
    exchangeId: v.id("exchangeRequests"),
    estimatedValue: v.number(),
    conditionScore: v.number(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.exchangeId, {
      status: "evaluated",
      estimatedValue: args.estimatedValue,
      conditionScore: args.conditionScore,
    });
  },
});
